[package]
name = "joblib"
version = "0.1.0"
authors = ["Andrei Dobre <andreidobre.web@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.23.0"

[build-dependencies]
protoc-rust = "2.0"
