[package]
name = "joblib"
version = "0.1.0"
authors = ["Andrei Dobre <andreidobre.web@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.4.3"
prost = "0.7.0"

[build-dependencies]
tonic-build = "0.4.2"
